           <th>
             Title
           </th>
           <th>
             Art
           </th>
           <th>
             Type
           </th>
           <th>
             Category
           </th>
           <th>
             Created
           </th>
           <th>
             Updated
           </th>
